name: Publish Package

on:
  push:
    branches:
      - main  # Executa somente na branch 'main'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checa o código do repositório
      - name: Check out code
        uses: actions/checkout@v3

      # Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Escolha a versão desejada do Python

      # Instala o Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Instala as dependências
      - name: Install dependencies
        run: poetry install

      # Publica no PyPI
      - name: Publish to PyPI
        env:
          POETRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build
